plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.hilt.android)
    alias(libs.plugins.navigation.safe.args)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace 'com.example.comicversev1'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.comicversev1"
        minSdk 24
        targetSdk 35
        versionCode 4
        versionName "1.1.1"

        buildConfigField "String", "BASE_URL", '"http://3.1.207.156:8080/api/"'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
    buildFeatures {
        viewBinding true
        buildConfig true
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation 'de.hdodenhof:circleimageview:3.1.0'
    implementation libs.lifecycle.viewmodel
    implementation libs.lifecycle.livedata
    implementation libs.lifecycle.runtime
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation libs.room.runtime
    annotationProcessor libs.room.compiler
    implementation libs.room.rxjava3
    implementation libs.retrofit
    implementation libs.retrofit.gson
    implementation libs.retrofit.rxjava3
    implementation libs.okhttp.logging
    implementation libs.gson
    implementation libs.rxjava3
    implementation libs.rxandroid
    implementation libs.hilt.android
    annotationProcessor libs.hilt.compiler
    implementation libs.paging.runtime
    implementation libs.paging.rxjava3
    implementation libs.glide
    annotationProcessor libs.glide.compiler

    // SwipeRefreshLayout for pull-to-refresh
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'

    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    // PhotoView for pinch-to-zoom
    implementation 'com.github.chrisbanes:PhotoView:2.3.0'

    // Kotlin Coroutines for Timer
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'

    // Lottie for animations
    implementation 'com.airbnb.android:lottie:6.4.0'
}